### ISSUE TITLE
[1.10.2 / Sponge 5.1.0-BETA-1961 / pjp-5.1.0-0.13.6] Sign portals lost function

### ISSUE THREAD

**Issue by mister-man** [trentech/ProjectPortals#32]
Hallo together,

I upgrqaded my minecraft Server (with pjw, and pjp) and it seems some sign portals lose after a restart their function. Some other work fine the whole time.

I didn't found any logs or errors to these problem.

Thanks.

**Comment by COLDYY1** [comment]
Hello mister-man!

I suggest you to remove these sign-portals and create new ones. If it still doesn't work I'll then recommend you delete the .data file in pjp folder. Otherwise you can also use an other way to transport yourself through. Something like an button or an pressure plate seems to be an good option according to me.

Best Regards,
COLDYY1

**Comment by trentech** [comment]
unable to reproduce. Try updating to latest release
