### ISSUE TITLE
I created a world called "GameLand", made a portal to it and then it renamed my overworld to Gameland

### ISSUE THREAD

**Issue by SirRicharalar** [trentech/ProjectPortals#39]
I have have two GameLand Worlds when I do /world List. 

I can't rename it back. how do i fix it?

**Comment by SirRicharalar** [comment]
Page 1:
https://gyazo.com/35024e58031d7c0db2795c5ff24cda78

Page 2:
https://gyazo.com/b8f6f730a8bac66b1fc076c0a2dad1cf

I'm using Nucleus to generate the new worlds. It was fine until I added this portal pluggin.

**Comment by COLDYY1** [comment]
Hello SirRicharalar!

You can't make actuall portals using an other world managements plugin. That means you have to use: "Project Worlds" For the portals to work properly. As far as I can understand "PJP" doesn't support Nucleus way to store the world data. Theirfor I suggest you using "PJW". Because "PJP" has full support for that plugin.

**Comment by trentech** [comment]
OK I don't know what the deal is hear but it's not from Project Portals

@COLDYY1 That's not true. PJP should work just fine with Nucleus.

**Comment by ktole1999** [comment]
@trentech thank you for that confirmation as i am about to deploy PJP to my server lol
