### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by EmanYm** [trentech/ProjectPortals#46]
Is there an off-site wiki for PJP I am not aware of?
I'm looking for a list of supported color names, particle effects (likely [minecraft default](http://minecraft.gamepedia.com/Particles#Types_of_particles) but your default "WITCH_SPELL" does not match the vanilla "witchSpell") and portal types (I could not find "PORTAL2" in my search on minecraft.gamepedia.com)

There is also a lack of explanation for the config.
What is the "legacy builder", and how does it differ from non-legacy?

**Comment by trentech** [comment]
No wiki yet. The particle effects do not correlate with Minecraft. Use tab completion in game to find them all.
Disabling legacy builder allows to create portals with a single click of a pre-built frame instead of building them during portal creation. It's not %100 working. I wouldn't recommend changing this.

**Comment by EmanYm** [comment]
You could always open up the GitHub wiki and grant access to people to add to it.  I don't know how it works on Github for wiki contributions, but you could put that in the hands of the people that use it.

**Comment by trentech** [comment]
I've been planning on requesting assistance in documentation. Haven't worked out the details yet.
