### ISSUE TITLE
Possible missing config line?

### ISSUE THREAD

**Issue by EmanYm** [trentech/ProjectPortals#55]
As I was editing PJC.conf, I noticed the "database=" line was missing from "settings.sql".  That line is present in "pjp.conf", but not in pjc
I added it to my file just in case.

**Comment by trentech** [comment]
So the sql settings in pjc are just connection settings that my other plugins to use. pjc doesn't have database which is why the key is not there. pjp should only contain database key under the sql node. Basically each plugin uses the connection settings from pjc, but each plugin uses it's own database, so it's specified in the plugin config. Hope that makes sense

PJC:
`settings.sql.enable=false`
`settings.sql.password=password`
`settings.sql.prefix=NONE`
`settings.sql.url="localhost:3306"`
`settings.sql.username=root`

PJP:
`settings.sql.database=pjp`

**Comment by EmanYm** [comment]
It does.  I'll remove the line I added.
