### ISSUE TITLE
Colour support for other particle types

### ISSUE THREAD

**Issue by EmanYm** [trentech/ProjectPortals#62]
It would be marvelous if I could have green enchanting glyph for a matrix-style "tare" between a steampunk world and a modern or futuristic world.

**Comment by trentech** [comment]
Unless something has changed since I last checked, colors are only supported by the REDSTONE particle in Sponge. Not much I can do to change that

**Comment by EmanYm** [comment]
According to [the wiki](http://minecraft.gamepedia.com/Commands#particle), `mobspell` and `mobspellambient` also support colouring, but like you said, it may not be supported by Sponge.

**Comment by trentech** [comment]
It's been a while since I've checked so they vary well could be supported now. Just out of curiosity have you attempted adding color variable to them? I coded it in a matter that it should work on any Sponge particle that has the ParticleOptions.COLOR attribute, so shouldn't need to update anything on my end.

**Comment by trentech** [comment]
Yeah it looks like in the API it's noted that the following should be supported

AMBIENT_MOB_SPELL
MOB_SPELL
REDSTONE_DUST

If they aren't working let me know. I'll have to update the notes in the plugin to include these effects

**Comment by EmanYm** [comment]
In a single player, vanilla map I can make the spell particals coloured.  PJP gives a message if I try to colour the mob spell effect.

**Comment by trentech** [comment]
Whats the message?

Also I'm reopening this issue

**Comment by EmanYm** [comment]
`MOB_SPELL` and `AMBIENT_MOB_SPELL` are not even on the list or supported.  It returns with `Too many arguments!` and a syntax example.
For anything else I get the message, `Colors currently only works with REDSTONE type`

**Comment by trentech** [comment]
Can you copy the whole command you're attempting to run?

**Comment by EmanYm** [comment]
`/portal create <name> <server> -b`
`/portal partical MOB_SPELL green`

**Comment by trentech** [comment]
partical should be particle

**Comment by EmanYm** [comment]
Yea, that's my typo here.  I did spell it correctly in the game.
I don't have the game loaded right now, though.

**Comment by trentech** [comment]
Yeah I'm at work so I have limited ability..I shouldn't even be on here lol.
Did you try doing the color in caps? I can't remember if they're case sensitive or not

**Comment by EmanYm** [comment]
They don't appear to be case sensitive.  I can change the particle to redstone and the colour to green in lower case.

**Comment by trentech** [comment]
Yeah it doesn't really make sense to me. Nowhere does my plugin care what the particle type is other than verifying that it supports color, so it should be giving different problems between different particles..I will have to look at it when I get home, right now it's just giving me a headache because I can't look into it from here.

**Comment by EmanYm** [comment]
https://i.gyazo.com/5484a6f53ba12c3c2467f725bcd126e9.png

**Comment by trentech** [comment]
Spelling particle wrong again...

**Comment by EmanYm** [comment]
Concentrate on work.  This can wait. 😛

**Comment by trentech** [comment]
So I've figure it out. They were never added to my Particles enum. I couldn't remember why at first but after adding them realized because they never looked right. The AMBIENT_MOB_SPELL are near invisible and have this wavy motion that I didn't really think went with the portal design. The MOB_SPELL I think are bugged because all I'm getting is white diamonds that seem to dart in a certain direction depending on the color value. It's pretty strange.

**Comment by EmanYm** [comment]
Could that be a sponge problem?  They work fine in vanilla single player.

**Comment by trentech** [comment]
Yeah I believe so but I'm going to look into it further because this particles are messed up

http://imgur.com/a/h3R1C

**Comment by trentech** [comment]
Opened an issue on SpongeCommon page. Looks to be getting resolved

https://github.com/SpongePowered/SpongeCommon/issues/1421
